Mission4_ejake370/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_ejake370.Models
{
    public class GradeCalculatorModel
    {
        [Required(ErrorMessage ="Value for {0} is required.")]
        [Range(0,100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float Assignments { get; set; }
        [Required(ErrorMessage = "Value for {0} is required.")]
        [Range(0, 100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float GroupProject { get; set; }
        [Required(ErrorMessage = "Value for {0} is required.")]
        [Range(0, 100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float Quizzes { get; set; }
        [Required(ErrorMessage = "Value for {0} is required.")]
        [Range(0, 100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float Midterm { get; set; }
        [Required(ErrorMessage = "Value for {0} is required.")]
        [Range(0, 100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float Final { get; set; }
        [Required(ErrorMessage = "Value for {0} is required.")]
        [Range(0, 100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public float Intex { get; set; }

    }
}

Mission4_ejake370/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4_ejake370.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Mission4_ejake370.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission4_ejake370/Views/Blah/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model GradeCalculatorModel;



<h3>Grade Calculator</h3>

<!--Form used to calculate final grade/letter grade-->
<p style="font-style:italic">Enter percentage for each grade category</p>

<form method="post" >
    <label>Assignments</label>
    <input id="assignments" asp-for="Assignments" /><br />
    <label>Group Project</label>
    <input id="grpProject"  asp-for="GroupProject"/><br />
    <label>Quizzes</label>
    <input id="quizzes" asp-for="Quizzes"/><br />
    <label>Midterm Exam</label>
    <input id="midterm" asp-for="Midterm"/><br />
    <label>Final Exam</label>
    <input id="final" asp-for="Final"/><br />
    <label>INTEX</label>
    <input id="intex" asp-for="Intex"/><br />
    <input id="calculate" type="submit" value="See Score" />


    <div asp-validation-summary="All"></div>

</form>

<p>Final Grade: <span class="score"></span> %</p>
<p>Letter Grade: <span class="letter_grade"></span></p>

<script src="~/js/calculator.js"></script>

Mission4_ejake370/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mission 5 - Jake Evans";
}


<h1>Jake Evans</h1>
<img src="img/IMG_5185 Large.jpeg" alt="Mountain Biking" class="center" /><br />
<h3>What I hope to learn from IS 413:</h3>
<p>
    I hope to develop a greater understanding of the MVC framework for web development
    I also hope that I can increase my marketability and job readiness. As we work with C#, I hope to strengthen
    my strongly-typed language skills and be more deliberate with my programming.
</p>

<h3>Top 3 Jobs After Graduation:</h3>
<ol>
    <li>Software Developer</li>
    <li>Full-Stack Web Developer</li>
    <li>Product Manager</li>
</ol>


<!--links to javascript and jquery-->

Mission4_ejake370/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <!-- Links to css and favicon (icon)-->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>

    <!-- Uses Tag helpers to create a dynamic navigation bar-->
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>


    <div>
        @RenderBody()
    </div>

    <!--Reference to JS-->
    <script src="~/lib/jquery-3.6.3.min.js"></script>

</body>
</html>